// Shared utilities for all platform content scripts.
//
// Each platform adapter imports (via shared execution context) these
// helpers, then registers its own selectors + review-parser. The adapter's
// job is to find review elements on the page, inject a "✨ AI Draft" button
// near each one, and when clicked, parse the review fields and ask the
// background service worker for a draft.

// Namespace everything so we don't clash with platform-page scripts
window.__reviewhub = window.__reviewhub || {};

(function () {
  if (window.__reviewhub.initialized) return;
  window.__reviewhub.initialized = true;

  const PLATFORM = null; // overridden by platform adapter

  // Inject the AI draft button next to a review element. `parseReview` must
  // return { platform, reviewer_name, rating, review_text, business_name? }.
  // `reviewEl` is the DOM node that logically wraps the review (the button
  // is appended to it or to a caller-provided host).
  window.__reviewhub.injectButton = function injectButton({ reviewEl, host, parseReview, platform }) {
    // Idempotency — don't inject twice
    if (reviewEl.dataset.rhInjected === '1') return;
    reviewEl.dataset.rhInjected = '1';

    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'rh-draft-btn';
    btn.innerHTML = '<span aria-hidden="true">✨</span> AI Draft Reply';
    btn.setAttribute('aria-label', 'Generate AI-drafted reply via ReviewHub');

    btn.addEventListener('click', async (e) => {
      e.preventDefault();
      e.stopPropagation();
      await handleDraftClick({ btn, reviewEl, parseReview, platform });
    });

    (host || reviewEl).appendChild(btn);
  };

  async function handleDraftClick({ btn, reviewEl, parseReview, platform }) {
    const original = btn.innerHTML;
    btn.disabled = true;
    btn.innerHTML = '<span class="rh-spinner"></span> Drafting…';

    try {
      const review = parseReview(reviewEl);
      if (!review || !review.review_text) {
        showToast('Couldn\'t parse this review — try refreshing the page.', 'error');
        return;
      }
      const payload = { platform, ...review };
      const response = await chrome.runtime.sendMessage({ type: 'DRAFT_REPLY', payload });

      if (!response?.ok) {
        const msg = response?.error === 'NOT_CONFIGURED'
          ? 'Click the ReviewHub extension icon to paste your token first.'
          : response?.error || 'Draft failed';
        if (response?.status === 402) {
          showToast(`${msg}${response.quota ? ` (${response.quota.used}/${response.quota.max} used)` : ''}`, 'error');
        } else {
          showToast(msg, 'error');
        }
        return;
      }

      await showDraftDialog({ draft: response.draft, source: response.source, review });
    } catch (err) {
      showToast(`Error: ${err?.message || 'unknown'}`, 'error');
    } finally {
      btn.disabled = false;
      btn.innerHTML = original;
    }
  }

  // Shows a small floating dialog with the draft text, a copy button, and a
  // close button. Platforms differ enough that auto-pasting into their
  // native reply field is unreliable — copy-to-clipboard works everywhere.
  async function showDraftDialog({ draft, source, review }) {
    // Remove any existing dialog first
    document.querySelectorAll('.rh-dialog-backdrop').forEach(el => el.remove());

    const backdrop = document.createElement('div');
    backdrop.className = 'rh-dialog-backdrop';

    const dialog = document.createElement('div');
    dialog.className = 'rh-dialog';
    dialog.setAttribute('role', 'dialog');
    dialog.setAttribute('aria-label', 'AI drafted reply');

    dialog.innerHTML = `
      <div class="rh-dialog-header">
        <span class="rh-logo">✨</span>
        <strong>AI-drafted reply</strong>
        <button class="rh-close" aria-label="Close">×</button>
      </div>
      <div class="rh-review-preview">
        <div class="rh-review-meta">
          <span class="rh-stars">${'★'.repeat(review.rating || 0)}${'☆'.repeat(5 - (review.rating || 0))}</span>
          <span class="rh-reviewer">${escapeHtml(review.reviewer_name || 'Customer')}</span>
        </div>
        <p class="rh-review-text">${escapeHtml((review.review_text || '').slice(0, 180))}${(review.review_text || '').length > 180 ? '…' : ''}</p>
      </div>
      <textarea class="rh-draft-text" rows="6">${escapeHtml(draft)}</textarea>
      <div class="rh-dialog-actions">
        <button class="rh-copy">Copy to clipboard</button>
        <span class="rh-source">${source === 'ai' ? 'Generated by Claude' : 'From template pool'}</span>
      </div>
    `;

    backdrop.appendChild(dialog);
    document.body.appendChild(backdrop);

    backdrop.addEventListener('click', (e) => { if (e.target === backdrop) backdrop.remove(); });
    dialog.querySelector('.rh-close').addEventListener('click', () => backdrop.remove());
    dialog.querySelector('.rh-copy').addEventListener('click', async () => {
      const text = dialog.querySelector('.rh-draft-text').value;
      try {
        await navigator.clipboard.writeText(text);
        const btn = dialog.querySelector('.rh-copy');
        btn.textContent = 'Copied ✓';
        setTimeout(() => { btn.textContent = 'Copy to clipboard'; }, 1500);
      } catch { /* noop */ }
    });

    // Esc to close
    const escHandler = (e) => { if (e.key === 'Escape') { backdrop.remove(); document.removeEventListener('keydown', escHandler); } };
    document.addEventListener('keydown', escHandler);
  }

  function escapeHtml(s) {
    return String(s ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#x27;');
  }

  // Non-blocking toast for error / info messages
  function showToast(message, kind = 'info') {
    const existing = document.querySelector('.rh-toast');
    if (existing) existing.remove();
    const toast = document.createElement('div');
    toast.className = `rh-toast rh-toast-${kind}`;
    toast.textContent = message;
    document.body.appendChild(toast);
    setTimeout(() => toast.remove(), 5000);
  }

  window.__reviewhub.showToast = showToast;
  window.__reviewhub.escapeHtml = escapeHtml;

  // MutationObserver watchdog — pages like Facebook lazy-load review cards,
  // so we re-scan whenever the DOM changes. Platform adapters provide a
  // `scan()` function that finds and injects on all unseen reviews.
  window.__reviewhub.observe = function observe(scan) {
    scan(); // initial pass
    const observer = new MutationObserver(() => {
      // Debounce re-scans at 300ms
      clearTimeout(window.__reviewhub._scanTimer);
      window.__reviewhub._scanTimer = setTimeout(scan, 300);
    });
    observer.observe(document.body, { childList: true, subtree: true });
  };
})();
