import React, { useEffect, useRef, useState, useMemo, lazy, Suspense } from 'react';
import { useParams } from 'react-router-dom';
import api from '../lib/api';
import usePageTitle from '../hooks/usePageTitle';
import useNoIndex from '../hooks/useNoIndex';
import useSocialMeta from '../hooks/useSocialMeta';
import { getStripeCheckoutUrl } from '../lib/checkout';

// Lazy-loaded: the LINE mockup is ~5KB of decorative SVG + animations,
// and only renders below the CTA fold. No reason to ship it in the
// initial bundle for prospects who close the tab after the first card.
const LineFlexCardMockup = lazy(() => import('../components/LineFlexCardMockup'));

// /audit-preview/<share_token> — public, no auth.
//
// The page a prospect lands on when the founder DMs them an outbound
// audit URL. Renders the prospect's own reviews + the AI-drafted
// replies side-by-side. Mobile-first because owners open DMs on
// phones.
//
// LOCKED TO LIGHT THEME. The founder may have dark mode set in the
// dashboard, but this page is shown to PROSPECTS who never opted in
// to anything. CSS vars (--rh-paper / --rh-ink / etc.) flip with the
// founder's preference and produced unreadable dark-on-dark draft
// text. Hardcoding literal hex values + colorScheme:'light' on the
// root container makes the page render identically regardless of OS,
// browser, or founder preference. Print-document treatment.
const COLORS = {
  paper: '#fbf8f1',     // warm cream background
  ink: '#1d242c',       // dark ink for primary text
  inkSoft: '#4a525a',   // muted dark for secondary text
  inkDim: '#9aa3ac',    // dimmer muted for tertiary
  ochre: '#c48a2c',     // brand accent for "REPLY SUGGESTIONS FOR" label
  tealDeep: '#1e4d5e',  // brand teal for buttons and "Suggested reply" label
  line: '#e6dfce',      // subtle border around cards
  divider: '#f0e9d8',   // softer than `line` — used INSIDE cards (review/draft separator)
                         // so the inside-the-card line doesn't visually merge with
                         // the outside-the-card border.
  cardBg: '#ffffff',    // pure white card on cream paper
  cardShadow: '0 1px 3px rgba(29,36,44,0.05), 0 1px 2px rgba(29,36,44,0.03)',
                         // tiny paper-lift; cream-on-cream borders alone left
                         // cards visually merging with background. Very subtle —
                         // not a SaaS-y elevation tier, just enough to read.
  star: '#f59e0b',      // amber for filled stars
  starEmpty: '#dcd4c0', // warm-neutral empty star (was #e5e7eb cool gray which
                         // fought the warm paper background)
};

// CTA A/B split — Variant E (permission-asking) vs control. Per
// docs/audit-preview-cta-variants.md. Tests the hypothesis that "Yes,
// keep the drafts coming" reads as lower-commitment opt-in than "Yes,
// set this up for me" (an imperative buy verb). Wave 4 (sent 5/12-5/13)
// is the first cohort; reply window closes 5/16.
//
// Deterministic per-token assignment — each prospect always sees the
// same variant across refreshes/devices. No DB change required; the
// signal reads from Plausible event names (`AuditRegisterClick` for
// control, `AuditRegisterClick_PermissionV` for variant). Sticky bar
// matches the same variant assignment so we don't cross-pollinate.
function assignCtaVariant(token) {
  if (!token) return 'control';
  let h = 0;
  for (let i = 0; i < token.length; i++) h = (h * 31 + token.charCodeAt(i)) | 0;
  return (Math.abs(h) % 2 === 0) ? 'control' : 'E';
}

export default function AuditPreview() {
  const { token } = useParams();
  const ctaVariant = useMemo(() => assignCtaVariant(token), [token]);
  const [state, setState] = useState({ status: 'loading', data: null, error: '' });
  usePageTitle(state.data?.business_name
    ? `${state.data.business_name} — Reply suggestions`
    : 'Audit preview · ReviewHub');
  useNoIndex(); // share-token URLs are per-prospect; never index them
  // Override the default site OG card so when the founder pastes this
  // URL into iMessage/Slack/LINE, the preview reads as
  // "AI reply drafts for {their business}" instead of the generic
  // marketing-site card. Bot/preview crawlers fetching the URL still
  // get filtered out of view-tracking notifications upstream.
  useSocialMeta(state.data?.business_name ? {
    title: `AI reply drafts for ${state.data.business_name}`,
    description: `${state.data.reviews?.filter(r => r.draft).length || ''} reply drafts ready to copy & paste — no signup needed. Generated by ReviewHub for ${state.data.business_name}.`,
    // Audit-specific OG card (different headline + sub-line than the
    // generic landing-page card). Per-prospect text personalization
    // lives in title/description above; the image is static because
    // generating per-business images needs a server-side renderer
    // we don't have yet.
    image: 'https://reviewhub.review/og-image-audit.png',
  } : undefined);

  useEffect(() => {
    if (!token) {
      setState({ status: 'error', data: null, error: 'No token' });
      return;
    }
    let cancelled = false;
    api.get(`/audit-previews/share/${encodeURIComponent(token)}`)
      .then(({ data }) => {
        if (!cancelled) setState({ status: 'ok', data, error: '' });
      })
      .catch((err) => {
        if (cancelled) return;
        const msg = err?.response?.status === 404
          ? 'This preview link has expired or doesn\'t exist. Ask the sender for a fresh one.'
          : 'Could not load the preview. Try refreshing.';
        setState({ status: 'error', data: null, error: msg });
      });
    return () => { cancelled = true; };
  }, [token]);

  // Scroll-depth funnel signal. Fires Plausible events at 25 / 50 / 75 / 100%
  // page-scrolled. Lets us tell "prospect bounced after 1 review card" from
  // "prospect read everything and ignored CTA" — totally different problems.
  // Only arms after data loads so the loading-spinner page doesn't pollute
  // the funnel with bogus 0% events.
  useEffect(() => {
    if (state.status !== 'ok') return;
    const fired = new Set();
    function onScroll() {
      const scrolled = window.scrollY + window.innerHeight;
      const total = document.documentElement.scrollHeight;
      if (total <= 0) return;
      const pct = (scrolled / total) * 100;
      const milestones = [25, 50, 75, 100];
      for (const m of milestones) {
        if (pct >= m && !fired.has(m)) {
          fired.add(m);
          if (typeof window.plausible === 'function') {
            try {
              window.plausible('AuditScrollDepth', { props: { depth: `${m}%` } });
            } catch { /* analytics down, swallow */ }
          }
        }
      }
    }
    window.addEventListener('scroll', onScroll, { passive: true });
    onScroll(); // fire 25% immediately if the page is already short
    return () => window.removeEventListener('scroll', onScroll);
  }, [state.status]);

  // Root style — applied to every state branch so loading/error/ok all
  // honour the light-mode lock. colorScheme:'light' tells the browser
  // not to auto-invert form controls, and the explicit background +
  // color ensure no inheritance from the founder's dashboard theme.
  const rootStyle = {
    background: COLORS.paper,
    color: COLORS.ink,
    colorScheme: 'light',
    minHeight: '100vh',
  };

  if (state.status === 'loading') {
    return (
      <div className="grid place-items-center px-4" style={rootStyle}>
        <div className="w-10 h-10 border-4 border-t-transparent rounded-full animate-spin" style={{ borderColor: COLORS.tealDeep, borderTopColor: 'transparent' }} aria-hidden="true" />
      </div>
    );
  }

  if (state.status === 'error') {
    return (
      <div className="grid place-items-center px-4 py-12" style={rootStyle}>
        <div className="max-w-md text-center">
          <p className="text-5xl mb-4" aria-hidden="true">🔗</p>
          <h1 className="text-xl font-bold mb-2" style={{ color: COLORS.ink }}>Preview not available</h1>
          <p className="text-sm" style={{ color: COLORS.inkSoft }}>{state.error}</p>
        </div>
      </div>
    );
  }

  const { business_name, reviews } = state.data;
  const totalDrafts = reviews.filter((r) => r.draft).length;

  return (
    <div style={rootStyle}>
      <StickyConversionBar
        businessName={business_name}
        token={token || ''}
        show={totalDrafts > 0}
        ctaVariant={ctaVariant}
      />
      <main className="max-w-3xl mx-auto px-5 py-8 md:py-16 pb-28 md:pb-16">
        {/* Header — sets context immediately so the prospect doesn't
            wonder "wait, who is this and what am I looking at?" Tightened
            on mobile so the first review card peeks above the fold —
            seeing your own review text is the "wait this is real" moment. */}
        <header className="mb-8 md:mb-10">
          <p className="text-xs font-mono uppercase tracking-widest mb-2" style={{ color: COLORS.ochre }}>
            Reply suggestions for
          </p>
          <h1 className="text-2xl md:text-4xl font-bold mb-2 md:mb-3" style={{ color: COLORS.ink, letterSpacing: '-0.02em' }}>
            {business_name}
          </h1>
          <p className="text-sm md:text-base leading-relaxed" style={{ color: COLORS.inkSoft }}>
            {totalDrafts} draft {totalDrafts === 1 ? 'reply' : 'replies'} ready to copy &amp; paste — no account needed.
          </p>
        </header>

        {/* Reviews + drafts — one card per review */}
        <div className="space-y-6">
          {reviews.map((r, i) => (
            <article
              key={i}
              className="rounded-2xl p-5 md:p-6"
              style={{
                background: COLORS.cardBg,
                border: `1px solid ${COLORS.line}`,
                boxShadow: COLORS.cardShadow,
              }}
            >
              {/* The review (what the customer wrote) */}
              <div className="mb-4">
                <div className="flex items-center justify-between gap-3 mb-2 flex-wrap">
                  <p className="text-sm font-semibold" style={{ color: COLORS.ink }}>
                    {r.reviewer_name || 'Anonymous'}
                  </p>
                  <span className="text-base" style={{ color: COLORS.star }} aria-label={`${r.rating} stars`}>
                    {'★'.repeat(r.rating)}
                    <span style={{ color: COLORS.starEmpty }}>{'★'.repeat(5 - r.rating)}</span>
                  </span>
                </div>
                <p className="leading-relaxed whitespace-pre-wrap" style={{ color: COLORS.inkSoft, fontSize: '15px' }}>
                  {r.text}
                </p>
              </div>

              {/* Divider — uses softer `divider` colour so the inside-card
                  separator doesn't visually merge with the outside-card border. */}
              <div className="h-px my-4" style={{ background: COLORS.divider }} />

              {/* The drafted reply */}
              {r.draft ? (
                <div>
                  <p
                    className="text-xs font-mono uppercase tracking-widest mb-2"
                    style={{ color: COLORS.tealDeep }}
                  >
                    Suggested reply
                  </p>
                  <p
                    className="leading-relaxed whitespace-pre-wrap"
                    style={{ color: COLORS.ink, fontSize: '15px' }}
                  >
                    {r.draft}
                  </p>
                  <CopyButton text={r.draft} />
                </div>
              ) : (
                <p className="text-xs italic" style={{ color: COLORS.inkDim }}>
                  Couldn't generate a draft for this one — usually means the review text was too short or in an unsupported language.
                </p>
              )}
            </article>
          ))}
        </div>

        {/* Primary CTA — placed at peak-interest moment, right after the
            drafts and BEFORE the educational footer. Footer-only pitch
            buries the conversion path; a real button here at the moment
            the prospect just read their own personalised replies captures
            intent that prose loses. */}
        {totalDrafts > 0 && (
          <section
            className="mt-10 rounded-2xl p-6 md:p-8 text-center"
            style={{ background: COLORS.tealDeep, color: '#fff' }}
          >
            <p
              className="text-xs font-mono uppercase tracking-widest mb-2"
              style={{ color: '#f5d8a7', opacity: 0.9 }}
            >
              {ctaVariant === 'E' ? 'This audit was free' : 'Want this on autopilot?'}
            </p>
            <h2 className="text-xl md:text-2xl font-bold mb-3" style={{ letterSpacing: '-0.01em' }}>
              {ctaVariant === 'E'
                ? `Want ReviewHub to keep drafting for ${business_name}?`
                : `Set this up for ${business_name} in 10 minutes`}
            </h2>
            <p className="text-sm leading-relaxed mb-5 max-w-md mx-auto" style={{ color: '#fdf2dc' }}>
              {ctaVariant === 'E' ? (
                <>
                  Connect Google once. Every new review pings you on LINE — with a
                  draft reply in your voice. Copy from LINE, paste in Google. $14/mo
                  (~฿499). <em>The drafts above stay yours regardless of what you decide.</em>
                </>
              ) : (
                <>
                  Connect Google once. New reviews ping you on LINE or Telegram — with an
                  AI-drafted reply in your voice. Copy, paste in Google. Replies that took
                  30 min each take 30 seconds. $14/mo (~฿499).
                </>
              )}
            </p>
            {/* Plausible tagged-events: clicking this fires either
                "AuditRegisterClick" (control) or "AuditRegisterClick_PermissionV"
                (Variant E) so we can read the A/B from Plausible without
                a DB column. See docs/audit-preview-cta-variants.md. */}
            {/* Primary CTA — was /register, now goes straight to Stripe
                Payment Link for the Starter tier. Cuts the prospect
                directly to checkout instead of a signup interstitial.
                Stripe redirects post-pay to /register?from=stripe&plan=starter
                so the customer creates their ReviewHub account after
                their card has been charged. Plausible event names
                preserved so funnel analysis still partitions control vs
                variant (V) CTA copy. */}
            <a
              href={getStripeCheckoutUrl('starter') || `/register?from=audit&business=${encodeURIComponent(business_name)}&token=${encodeURIComponent(token || '')}&v=${ctaVariant}`}
              className={`${ctaVariant === 'E' ? 'plausible-event-name=AuditRegisterClick_PermissionV' : 'plausible-event-name=AuditRegisterClick'} plausible-event-source=audit-cta plausible-event-plan=starter inline-block px-6 py-3 rounded-lg text-sm font-semibold transition-transform hover:scale-105`}
              style={{ background: COLORS.cardBg, color: COLORS.tealDeep }}
            >
              {ctaVariant === 'E' ? 'Yes, keep the drafts coming →' : 'Yes, set this up for me →'}
            </a>
            <p className="text-xs mt-3" style={{ color: '#fdf2dc', opacity: 0.85 }}>
              No credit card to start · 30-day refund window · cancel anytime
            </p>
            {/* Async CTAs — Wave 1-4 diagnostic (2026-05-15) showed 35%
                audit-open rate but 0 replies across 22 sends; Chakrabongse
                viewed 14× with no reply. The Stripe CTA above is high-
                friction (pay before they trust). Some prospects will want
                to ask a question first, but won't take a sales call (and
                the founder doesn't take them anyway — written-only per
                about_me_observed.md). Two async options surfaced here,
                not buried in the footer: LINE chat for Thai/SE Asia
                prospects (their daily app), email for everyone else.
                Both lead to the same human (Earth). */}
            <div className="mt-5 pt-5 border-t" style={{ borderColor: 'rgba(253,242,220,0.18)' }}>
              <p className="text-sm" style={{ color: '#f5d8a7', opacity: 0.95 }}>
                Or — ask first, no signup:
              </p>
              <div className="flex flex-wrap items-center justify-center gap-3 mt-3">
                {/* LINE OA Basic ID @024hjpcv is the production ReviewHub
                    bot. The line.me/R/ti/p/<id> deep link opens LINE app
                    on mobile (best path for Thai prospects) and falls back
                    to LINE's web add-friend page on desktop. */}
                <a
                  href="https://line.me/R/ti/p/@024hjpcv"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="plausible-event-name=AuditLineChatClick inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-transform hover:scale-105"
                  style={{ background: '#06c755', color: '#fff' }}
                >
                  <span aria-hidden="true" style={{ fontSize: '16px' }}>💬</span>
                  Chat on LINE
                </a>
                <a
                  href={`mailto:earth.reviewhub@gmail.com?subject=${encodeURIComponent(`Re: ${business_name} reply drafts`)}&body=${encodeURIComponent(`Hi Earth,\n\nQuestion about the drafts for ${business_name}: `)}`}
                  className="plausible-event-name=AuditFounderReplyClick inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold transition-transform hover:scale-105"
                  style={{ background: 'rgba(255,255,255,0.12)', color: '#fff', border: '1px solid rgba(255,255,255,0.25)' }}
                >
                  <span aria-hidden="true" style={{ fontSize: '16px' }}>✉</span>
                  Email me
                </a>
              </div>
              <p className="text-xs mt-3" style={{ color: '#f5d8a7', opacity: 0.85 }}>
                I'm Earth, the solo founder. A one-line "tell me more" or
                "not for me" is genuinely useful either way — I reply within
                a day, async, no calls.
              </p>
            </div>
            <p className="text-xs mt-2 max-w-md mx-auto font-mono uppercase tracking-widest" style={{ color: '#f5d8a7', opacity: 0.85 }}>
              LINE notifications live now —{' '}
              <a
                href="/line"
                className="plausible-event-name=AuditLineHelpClick"
                style={{ color: '#f5d8a7', textDecoration: 'underline' }}
              >
                see how it works →
              </a>
            </p>
          </section>
        )}

        {/* LINE notification mockup — shows the prospect what the actual
            in-product experience looks like on their phone. Addresses
            intervention #5 from the audit-preview friction teardown
            (2026-05-11): the page mentions LINE 2× but doesn't SHOW the
            flow. Static screenshot would be cheaper; an interactive mockup
            lets the prospect tap Copy and feel the haptic feedback for
            themselves before signing up. */}
        {totalDrafts > 0 && (
          <section className="mt-10">
            <p
              className="text-xs font-mono uppercase tracking-widest mb-3 text-center"
              style={{ color: COLORS.ochre }}
            >
              What this looks like on your phone
            </p>
            <Suspense fallback={<div style={{ height: 320 }} aria-hidden="true" />}>
              <LineFlexCardMockup />
            </Suspense>
            <p className="text-xs text-center mt-2" style={{ color: COLORS.inkDim }}>
              Tap <strong>Copy</strong> to feel the flow yourself.
            </p>
          </section>
        )}

        {/* Inline FAQ — addresses the four objections SMB owners actually
            think when first looking at AI-drafted review replies. Each one
            is the kind of question that, if unanswered, makes the prospect
            close the tab. Inline collapsibles (native <details>) are fine
            for SEO + accessibility, no JS needed. */}
        {totalDrafts > 0 && (
          <section className="mt-10">
            <h3
              className="text-sm font-mono uppercase tracking-widest mb-4"
              style={{ color: COLORS.inkDim }}
            >
              Common questions
            </h3>
            <div className="space-y-2">
              {[
                {
                  q: 'Can I edit the replies before they post?',
                  a: 'Always. Every draft pings you on LINE — you review, edit, or rewrite before anything goes to Google. Nothing posts without your approval; you copy the final reply and paste it into Google yourself (one-tap auto-post launches once Google approves our API access).',
                },
                {
                  q: 'What if a reply is wrong or off-tone?',
                  a: 'You edit it. ReviewHub learns from every edit you make — over time the drafts match your voice more closely. The first week is the worst; week three usually needs only minor tweaks.',
                },
                {
                  q: 'How does it handle 1-star or angry reviews?',
                  a: 'Differently than 5-stars. Negative reviews get drafts that acknowledge specifically what went wrong, take ownership without "but", and invite the reviewer back privately — never the canned "we strive for excellence" template.',
                },
                {
                  q: 'Is my Google account / data safe?',
                  a: 'ReviewHub reads reviews via Google\'s official Places API (read-only) — no password stored, no other Google data accessed. Posting replies is currently tap-to-copy: we draft on LINE / Telegram, you paste in Google\'s reply box. Auto-post via Google\'s Business Profile API launches once our access is approved (case 8-9395000041442, submitted 2026-05-09). You can revoke access anytime from your Google account settings.',
                },
                {
                  q: 'What if I cancel mid-month?',
                  a: 'You keep access through the end of the billing period, then it ends. No clawback of replies already posted. 30-day refund window on the first month, no questions asked.',
                },
              ].map((item, i) => (
                <details
                  key={i}
                  className="rounded-xl"
                  style={{ background: COLORS.cardBg, border: `1px solid ${COLORS.line}` }}
                  onToggle={(e) => {
                    // Funnel signal: which FAQ items get expanded most often =
                    // which objections are top-of-mind. Lets us reorder /
                    // rewrite the page based on what readers actually care
                    // about, vs guessing. Only fire on open, not close, and
                    // pass the question as a prop for per-question breakdown.
                    if (!e.target.open) return;
                    if (typeof window.plausible === 'function') {
                      try {
                        window.plausible('AuditFAQOpen', { props: { q: item.q.slice(0, 60) } });
                      } catch { /* swallow */ }
                    }
                  }}
                >
                  <summary
                    className="px-4 py-3 cursor-pointer text-sm font-semibold list-none"
                    style={{ color: COLORS.ink }}
                  >
                    {item.q}
                  </summary>
                  <p
                    className="px-4 pb-4 pt-1 text-sm leading-relaxed"
                    style={{ color: COLORS.inkSoft }}
                  >
                    {item.a}
                  </p>
                </details>
              ))}
            </div>
          </section>
        )}

        {/* Footer — context + the "no pressure" personal note. Pulled
            here from the CTA card so the conversion-moment teal panel
            is button-focused, not text-overloaded. */}
        <footer
          className="mt-12 pt-8 border-t text-sm leading-relaxed"
          style={{ borderColor: COLORS.line, color: COLORS.inkSoft }}
        >
          <p className="mb-3">
            <strong style={{ color: COLORS.ink }}>Not ready to sign up?</strong>{' '}
            Just reply to my email — I'm Earth, the solo founder building this
            in Bangkok (
            <a
              href="/about"
              style={{ color: COLORS.tealDeep, textDecoration: 'underline' }}
            >
              more about me →
            </a>
            ), and a one-line "tell me more" or "not for me, here's why" is
            genuinely useful either way. Or keep using these drafts — the link
            above stays live for 30 days.
          </p>
          <p className="text-xs" style={{ color: COLORS.inkDim }}>
            <a
              href="https://reviewhub.review/"
              style={{ color: COLORS.tealDeep, fontWeight: 600 }}
            >
              reviewhub.review →
            </a>
          </p>
        </footer>
      </main>
    </div>
  );
}

// Sticky conversion bar — visible at the bottom of the viewport once the
// prospect has scrolled past the header. Fixes the buried-CTA problem:
// previously the only "Set this up" button lived below 5 review cards, so
// a prospect who got value from the drafts and tab-closed never saw the
// signup path. With the sticky bar, the CTA is always within tap reach.
//
// Behaviour:
//  - Hidden on initial load (header still in view; no need to compete
//    with the page header CTA energy).
//  - Appears once the user has scrolled past ~250px (past the page
//    header into the review cards).
//  - Dismissible — a small × in the bar hides it for the rest of the
//    page-view (sessionStorage flag, not localStorage; comes back on
//    next visit).
//  - Same plausible-event-name as the in-page CTA so we can tell which
//    surface drove the click in funnel analysis (event-prop "source").
function StickyConversionBar({ businessName, token, show, ctaVariant = 'control' }) {
  const [dismissed, setDismissed] = useState(false);

  if (!show || dismissed) return null;

  // No scroll gate. Earlier versions waited for `window.scrollY > 250`
  // before appearing, but on prod the window scroll event reliably did
  // NOT fire even though `document.documentElement.scrollTop` advanced
  // (verified via Chrome MCP probe — same-origin programmatic scroll
  // didn't trigger a window scroll listener; the underlying cause was
  // unclear and not worth a deep dive for a CTA bar). The simpler
  // version: always-visible when drafts exist. The bar lives at the
  // viewport bottom so it doesn't compete with the page header on
  // first paint, and dismissal still works per-session via the ×
  // button.
  function handleDismiss() {
    setDismissed(true);
  }

  return (
    <div
      role="region"
      aria-label="Sign-up call to action"
      className="fixed bottom-0 left-0 right-0 z-40"
      style={{
        background: COLORS.tealDeep,
        color: '#fff',
        boxShadow: '0 -2px 12px rgba(29,36,44,0.12)',
        paddingBottom: 'max(env(safe-area-inset-bottom), 0px)',
      }}
    >
      <div className="max-w-3xl mx-auto px-4 py-3 flex items-center gap-3">
        <p className="text-xs sm:text-sm flex-1 leading-snug">
          <span className="font-semibold">
            {ctaVariant === 'E' ? 'Keep the drafts coming?' : 'Want this on autopilot?'}
          </span>{' '}
          <span className="hidden sm:inline" style={{ color: '#fdf2dc' }}>
            New reviews ping you on LINE or Telegram. $14/mo (~฿499).
          </span>
        </p>
        <a
          href={getStripeCheckoutUrl('starter') || `/register?from=audit&business=${encodeURIComponent(businessName || '')}&token=${encodeURIComponent(token || '')}&source=sticky&v=${ctaVariant}`}
          className={`${ctaVariant === 'E' ? 'plausible-event-name=AuditRegisterClick_PermissionV' : 'plausible-event-name=AuditRegisterClick'} plausible-event-source=sticky plausible-event-plan=starter inline-block px-4 py-2 rounded-lg text-xs sm:text-sm font-semibold whitespace-nowrap transition-transform hover:scale-105`}
          style={{ background: COLORS.cardBg, color: COLORS.tealDeep, minHeight: '40px', display: 'inline-flex', alignItems: 'center' }}
        >
          {ctaVariant === 'E' ? 'Keep the drafts — $14/mo →' : 'Set this up — $14/mo →'}
        </a>
        {/* Parallel low-friction CTA on the sticky bar — Wave 4 diagnostic
            showed audit views convert to interest but never to reply
            because the only visible action was signup. Pre-filled mailto
            to founder gives a softer path. Hidden on xs to keep the bar
            tappable on phone (where the primary signup button needs the
            full width). */}
        <a
          href={`mailto:earth.reviewhub@gmail.com?subject=${encodeURIComponent(`Re: ${businessName || 'reply drafts'}`)}&body=${encodeURIComponent(`Hi Earth,\n\nQuestion about the drafts: `)}`}
          className="plausible-event-name=AuditFounderReplyClick plausible-event-source=sticky hidden md:inline-flex items-center px-3 py-2 text-xs sm:text-sm whitespace-nowrap underline hover:no-underline"
          style={{ color: '#fdf2dc', minHeight: '40px' }}
        >
          or reply →
        </a>
        <button
          type="button"
          onClick={handleDismiss}
          aria-label="Dismiss sign-up bar"
          className="opacity-70 hover:opacity-100 transition-opacity"
          style={{ color: '#fdf2dc', minHeight: '32px', minWidth: '32px' }}
        >
          ✕
        </button>
      </div>
    </div>
  );
}

// Per-card copy button. Lives at the value-delivery moment so it gets
// dedicated styling: WCAG-passing 44px tap target, clipboard icon for
// affordance, and a 1.6s "Copied ✓" state-swap so the prospect sees the
// click landed (the previous silent version triggered repeat-click
// frustration in critique).
function CopyButton({ text }) {
  const [copied, setCopied] = useState(false);
  const timerRef = useRef(null);

  // Clear the timeout on unmount so a tab-switched-mid-copy doesn't leak.
  useEffect(() => () => { if (timerRef.current) clearTimeout(timerRef.current); }, []);

  async function handleClick() {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Clipboard blocked (insecure context, permissions). Still show
      // "copied" so the user gets feedback; if it really didn't copy,
      // they'll notice when they paste and a re-click is one tap away.
    }
    // Funnel signal: lets us count, of N audit-page views, how many
    // prospects actually copied at least one draft. Separates "looked
    // and left" from "got value, didn't sign up." The two need
    // different fixes.
    if (typeof window.plausible === 'function') {
      try { window.plausible('AuditCopyClick'); } catch { /* swallow */ }
    }
    setCopied(true);
    if (timerRef.current) clearTimeout(timerRef.current);
    timerRef.current = setTimeout(() => setCopied(false), 1600);
  }

  return (
    <button
      type="button"
      onClick={handleClick}
      aria-live="polite"
      className="mt-4 inline-flex items-center gap-2 text-sm font-semibold px-4 py-2.5 rounded-lg transition-all"
      style={{
        background: copied ? COLORS.cardBg : COLORS.tealDeep,
        color: copied ? COLORS.tealDeep : '#fff',
        border: `1px solid ${COLORS.tealDeep}`,
        minHeight: '44px',
      }}
    >
      {copied ? (
        <>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied
        </>
      ) : (
        <>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
            <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
          </svg>
          Copy reply
        </>
      )}
    </button>
  );
}
